[project]
name = "sBTC-HashPort"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/sBTC-HashPort/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.ft-trait]
path = "contracts/ft-trait.clar"

[contracts.sBTC-HashPort]
path = "contracts/sBTC-HashPort.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
